### PR TITLE
fix windows - update lib name and README

### PR DESCRIPTION
**Pull request by pietroppeter**
Hi, thanks for rnim!

I have tested rnim on Windows and this is the easy fix that is required to make it work (just change name of lib to `R.dll` and no need to set `R_HOME`). Only with that (and the shared library available in the path), I am able to run succesfully `nim r tests\tRfromNim.nim`.

I have updated the README accordingly.

I have not tested how to call nim from R.

### CODE REVIEW

**Comment by pietroppeter** [comment]
ok, no. I do have to set R_HOME if I use it from another location (not sure why, it is working fine when I test from the rnim repo; if I import from another location it works only if I set R_HOME). I will update the README

**Comment by pietroppeter** [comment]
ok, now it is ready!

**Comment by Vindaar** [comment]
Thanks a lot for this! 

And this reminds me I really need to get back to working on this... :)

**Comment by pietroppeter** [comment]
You are welcome!

One of the drafts of the upcoming blog I am working on, uses rnim: https://pietroppeter.github.io/nblog/drafts/display_multidim_arrays.html
As you can see one of the issue I have is how to print R objects the same way they are shown in the interpreter (also some object details get printed).

Anyway this got me very interested in understanding better how R works and these are some interesting references about it:

- https://adv-r.hadley.nz/index.html
- https://github.com/hadley/r-internals

**Comment by Vindaar** [comment]
Oh, that's nice!

Regarding pretty printing of tensors, I wrote this a few months back:
https://gist.github.com/Vindaar/ac49c9caf063c04caaf74dcae08eca79

**Comment by pietroppeter** [comment]
Ah, nice, I guess I might steal something (with proper attribution) ;)

**Comment by Vindaar** [comment]
Of course, feel free to do that! That's what it's for after all.

I wrote it a few months ago when @mratsim mentioned pretty printing tensors for higher dimensionality being difficult as an attempt to see if I could make it work. In the end I didn't do anything with it, mostly because I was too lazy to 1. check if I'm doing everything correctly and 2. (the main reason) didn't feel like wasting time putting the output into some nice ASCII art, haha. The approach R seems to take is very similar to what I'm doing in that gist for the `pretty` proc as far as I can tell.

**Pull request merged**
